#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "monerod"
name = "Monero Daemon"
description.en = "App to run the monero daemon for the private, decentralized cryptocurrency monero."

version = "1.0~ynh1"

maintainers = ["mari"]

[upstream]
# NB: Only the "license" key is mandatory. Remove entries for which there's no relevant data
license = "BSD-3-Clause" # you can see the available licenses identifiers list here: https://spdx.org/licenses/
website = "https://www.getmonero.org/"
admindoc = "https://docs.getmonero.org/running-node/monerod-systemd/"
userdoc = "https://docs.getmonero.org/interacting/overview/"
code = "github.com/monero-project/monero"

fund = "monero:84DreyVPzbgSLJC31b42ag2CUujt1GMuzGWkqBpqad2GWaiULRPX4eD8Y3aVJvHjzb56JQKodLudNJt4grBdgcXEAaejtEQ"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
# i'm pretty sure monero runs in all the architectures yunohost supports
architectures = "all"
multi_instance = false

ldap = "not_relevant"

sso = "not_relevant"

# monero is really resource intensive
# https://docs.getmonero.org/running-node/monerod-systemd/#assumptions
# 120G because even if you run a pruned node you probably want more storage for when the blockchain grows
disk = "120G"
ram.runtime = "4G"

[install]
    [install.prune]
    ask.en = "Prune the blockchain?"
    help.en = "Pruning the blockchain helps the network less but significantly reduces the storage needed to store it. By default it doesn't."
    type = "boolean"
    default = false

    [install.rpc_node]
    ask.en = "Advertise this node as an RPC node?"
    # TODO: How resource intensive is it?
    help.en = "Advertising this node as an RPC node provides another service to the network as it allows people without a full node to connect to it. However, it may be resource intensive."
    type = "boolean"
    default = false

[resources]
    # See the packaging documentation for the full set
    # of explanation regarding the behavior and properties for each of those

    [resources.system_user]
    # This will provision/deprovision a unix system user

    [resources.install_dir]
    # This will create/remove the install dir as /var/www/$app
    # and store the corresponding setting $install_dir

    [resources.data_dir]
    # This will create/remove the data dir as /home/yunohost.app/$app
    # and store the corresponding setting $data_dir

    # todo: research if we really need to expose both udp and tcp
    [resources.ports]
    main.default = 18080
    main.fixed = true
    main.exposed = Both

    rpc_port.default = 18089
    rpc_port.fixed = true
    rpc_port.exposed = Both

    zmq_port.defaut = 18081
    zmq_port.fixed = true
    zmq_port.exposed = Both

    [resources.apt]

    packages = [""]

    extras.tor.repo = "deb https://deb.torproject.org/torproject.org stable main"
    extras.tor.key = "https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc"
    extras.tor.packages = ["tor", "deb.torproject.org-keyring"]
    
    extras.i2p.repo = "deb https://repo.i2pd.xyz/debian bookworm main"
    extras.i2p.key = "https://repo.i2pd.xyz/r4sas.gpg"
    extras.i2p.packages = "i2pd"
