#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

ynh_backup "$install_dir"

#=================================================
# BACKUP THE DATA DIR
#=================================================

# backuping the blockchain doesn't sound like a good idea so we'll just backup the tor hidden service
ynh_backup "$data_dir/tor"
# backup the file with the i2p key for our i2p site (i think it's an eepsite?)
ynh_backup "/var/lib/i2pd/monero-mainnet.dat"

#=================================================
# BACKUP SYSTEM CONFIGURATION
#=================================================

# Backup the systemd service unit
ynh_backup "/etc/systemd/system/$app.service"

# Backup the logrotate configuration
ynh_backup "/etc/logrotate.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
