#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

### Install parameters are automatically saved as settings
###
### Settings are automatically loaded as bash variables
### in every app script context, therefore typically these will exist:
### - $domain
### - $path
### - $language
### ... etc
###
### Resources defined in the manifest are provisioned prior to this script
### and corresponding settings are also available, such as:
### - $install_dir
### - $port
### - $db_name
### ...
###
### $app is the app id (i.e. 'example' for first install,
### or 'example__2', '__3'... for multi-instance installs)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

gpg --import binaryfate.asc

wget -O "$install_dir/hashes.txt" "https://www.getmonero.org/downloads/hashes.txt"

gpg --verify "$install_dir/hashes.txt" 2>&1 | grep "Good signature" || ynh_die "Bad signature for hashes.txt"

architecture=$(dpkg --print-architecture)

case "$architecture" in
    "amd64")
        wget --content-disposition -P -q "$install_dir" "https://downloads.getmonero.org/cli/linux64"
        ;;
    "arm64")
        wget --content-disposition -P -q "$install_dir" "https://downloads.getmonero.org/cli/linuxarm8"
        ;;
    "riscv64")
        wget --content-disposition -P -q "$install_dir" "https://downloads.getmonero.org/cli/linuxriscv64"
        ;;
    "i386")
        wget --content-disposition -P -q "$install_dir" "https://downloads.getmonero.org/cli/linux32"
        ;;
    # i think armhf is armv7 but im not sure. todo: check
    "armhf")
        wget --content-disposition -P -q "$install_dir" "https://downloads.getmonero.org/cli/linuxarm7"
        ;;
    *)
        ynh_die "Unsupported architecture: $architecture"
        ;;
esac

cd "$install_dir"
sha256sum -c "hashes.txt" --ignore-missing 2>&1 | grep OK || ynh_die "Bad hash for monero.tar.bz2"

# we don't delete the other monero binaries but it should be okay i think. we should have storage for an extra 150~ MB
find "$install_dir" -type f -name "monero-linux*tar.bz2" -execdir tar xvf {} \;
find "$install_dir" -type f -name "monero-linux*tar.bz2" -execdir rm {} \;
monero_dir=$(find "$install_dir" -type d -name "monero-*")
find "$monero_dir" -type f -exec mv {} . \;
rm -r "$monero_dir"

### $install_dir will automatically be initialized with some decent
### permission by default... however, you may need to recursively reapply
### ownership to all files such as after the ynh_setup_source step
chown -R "$app:www-data" "$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

### You can add specific configuration files.
###
### Typically, put your template conf file in ../conf/your_config_file
### The template may contain strings such as __FOO__ or __FOO_BAR__,
### which will automatically be replaced by the values of $foo and $foo_bar
###
### ynh_config_add will also keep track of the config file's checksum,
### which later during upgrade may allow to automatically backup the config file
### if it's found that the file was manually modified
###
### Check the documentation of `ynh_config_add` for more info.

ynh_script_progression "Making onion serivce..."

cat >> "$install_dir/monero_tor.conf" << EOF
HiddenServiceDir $data_dir/tor/
HiddenServicePort 18089 127.0.0.1:18089    # interface for wallet ("RPC")
HiddenServicePort 18084 127.0.0.1:18084    # interface for P2P network
EOF

cat >> "/etc/tor/torrc" << EOF
%include $install_dir/monero_tor.conf
EOF

chmod 444 "$install_dir/monero_tor.conf"

mkdir -p "$data_dir/tor/"
chown -R "debian-tor:debian-tor" "$data_dir/tor/"
chmod 775 "$data_dir/tor/"

ynh_systemctl --service="tor" --action="enable"
ynh_systemctl --service="tor" --action="reload"

ynh_script_progression "Sleeping for 15 seconds to allow tor to start and create the onion service..."
sleep 15s

chmod 775 "$data_dir/tor/hostname"

onion_hostname=$(cat "$data_dir/tor/hostname")

ynh_script_progression "Onion hostname: $onion_hostname"

ynh_script_progression "Making I2P serivce..."

cat >> /etc/i2pd/tunnels.conf.d/monero-mainnet.conf << EOF
[monero-node]
type = server
host = 127.0.0.1
# Anonymous inbound port
port = 18085
inport = 0
keys = monero-mainnet.dat

[monero-rpc]
type = server
host = 127.0.0.1
# Restricted RPC port
port = 18089
keys = monero-mainnet.dat
EOF

chmod 444 /etc/i2pd/tunnels.conf.d/monero-mainnet.conf

ynh_systemctl --service_name="i2pd" --action="reload"

i2p_hostname=$(curl -s http://127.0.0.1:7070/?page=i2p_tunnels | grep -Eo "[a-zA-Z0-9./?=_%:-]*" | grep "18089")

ynh_script_progression "I2P hostname: $i2p_hostname"

ynh_config_add --template="monerod.conf" --destination="$install_dir/monerod.conf"

# FIXME: this should be handled by the core in the future
### You may need to use chmod 600 instead of 400,
### for example if the app is expected to be able to modify its own config
chmod 400 "$install_dir/monerod.conf"
chown "$app:$app" "$install_dir/monerod.conf"

### For more complex cases where you want to replace stuff using regexes,
### you shoud rely on ynh_replace (which is basically a wrapper for sed)
### When doing so, you also need to manually call ynh_store_file_checksum
###
### ynh_replace --match="match_string" --replace="replace_string" --file="$install_dir/some_config_file"
### ynh_store_file_checksum "$install_dir/some_config_file"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

### `ynh_config_add_systemd` is used to configure a systemd script for an app.
### It can be used for apps that use sysvinit (with adaptation) or systemd.
### Have a look at the app to be sure this app needs a systemd script.
### `ynh_config_add_systemd` will use the file conf/systemd.service
### If you're not using these lines:
###   - You can remove those files in conf/.
###   - Remove the section "BACKUP SYSTEMD" in the backup script
###   - Remove also the section "STOP AND REMOVE SERVICE" in the remove script
###   - As well as the section "RESTORE SYSTEMD" in the restore script
###   - And the section "SETUP SYSTEMD" in the upgrade script

# Create a dedicated systemd config
ynh_config_add_systemd

### `yunohost service add` integrates a service in YunoHost. It then gets
### displayed in the admin interface and through the others `yunohost service` commands.
### (N.B.: this line only makes sense if the app adds a service to the system!)
### If you're not using these lines:
###   - You can remove these files in conf/.
###   - Remove the section "REMOVE SERVICE INTEGRATION IN YUNOHOST" in the remove script
###   - As well as the section "INTEGRATE SERVICE IN YUNOHOST" in the restore script
###   - And the section "INTEGRATE SERVICE IN YUNOHOST" in the upgrade script

### Additional options starting with 3.8:
###
### --needs_exposed_ports "$port" a list of ports that needs to be publicly exposed
###                               which will then be checked by YunoHost's diagnosis system
###                               (N.B. DO NOT USE THIS if the port is only internal!!!)
###
### --test_status "some command"  a custom command to check the status of the service
###                               (only relevant if 'systemctl status' doesn't do a good job)
###
### --test_conf "some command"    some command similar to "nginx -t" that validates the conf of the service
###
### Re-calling 'yunohost service add' during the upgrade script is the right way
### to proceed if you later realize that you need to enable some flags that
### weren't enabled on old installs (be careful it'll override the existing
### service though so you should re-provide all relevant flags when doing so)
# yunohost service add "$app" --description="A short description of the app" --log="/var/log/$app/$app.log"

### `ynh_config_add_logrotate` is used to configure a logrotate configuration for the logs of this app.
### Use this helper only if there is effectively a log file for this app.
### If you're not using this helper:
###   - Remove the section "BACKUP LOGROTATE" in the backup script
###   - Remove also the section "REMOVE LOGROTATE CONFIGURATION" in the remove script
###   - As well as the section "RESTORE THE LOGROTATE CONFIGURATION" in the restore script
###   - And the section "SETUP LOGROTATE" in the upgrade script

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate --logfile="$data_dir/monero.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

### `ynh_systemctl` is used to start a systemd service for an app.
### Only needed if you have configure a systemd service
### If you're not using these lines:
###   - Remove the section "STOP SYSTEMD SERVICE" and "START SYSTEMD SERVICE" in the backup script
###   - As well as the section "START SYSTEMD SERVICE" in the restore script
###   - As well as the section"STOP SYSTEMD SERVICE" and "START SYSTEMD SERVICE" in the upgrade script
###   - And the section "STOP SYSTEMD SERVICE" and "START SYSTEMD SERVICE" in the change_url script

# Start a systemd service
ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
