#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================
source _common.sh
source /usr/share/yunohost/helpers

### For remove operations:
### - the core will deprovision every resource defined in the manifest **after** this script is ran
### this includes removing the install directory, and data directory (if --purge was used)

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

### This should be a symetric version of what happens in the install script

# i don't think it's necessary to remove tor and i2pd

grep -vF "%include /etc/tor/monero_tor.conf" "/etc/tor/torrc" > /tmp/temp_file && mv /tmp/temp_file "/etc/tor/torrc"

ynh_systemctl --service="tor" --action="reload"

ynh_safe_rm "/var/lib/tor/monero"
ynh_safe_rm "/etc/tor/monero_tor.conf"

ynh_safe_rm "/etc/i2pd/tunnels.conf.d/monero-mainnet.conf"
ynh_safe_rm "/var/lib/i2pd/monero-mainnet.dat"

ynh_systemctl --service="i2pd" --action="reload"

ynh_config_remove_logrotate

ynh_config_remove_systemd

ynh_safe_rm "$install_dir"
ynh_safe_rm "$data_dir"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
