#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================
source _common.sh
source /usr/share/yunohost/helpers

### Settings are automatically loaded as bash variables
### in every app script context, therefore typically these will exist:
### - $domain
### - $path
### - $language
### - $install_dir
### - $port
### ...

### In the context of upgrade,
### - resources are automatically provisioned / updated / deleted (depending on existing resources)
### - a safety backup is automatically created by the core and will be restored if the upgrade fails

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading monerod..."

# check if there's an update and we're not just redownloading the same version or an older one

wget -O "$install_dir/hashes_new.txt" "https://www.getmonero.org/downloads/hashes.txt"

new_verification=$(gpgv "hashes_new.txt")

new_signature_date_line=$(grep "Signature made" "$new_verification")

new_date_string=$(awk '{print $4, $5, $6, $7, $8}' <<< "$new_signature_date_line")

new_date=$(date -d "$new_date_string" +"%s")

old_verification=$(gpgv "hashes.txt")

old_signature_date_line=$(grep "Signature made" "$new_verification")

old_date_string=$(awk '{print $4, $5, $6, $7, $8}' <<< "$old_signature_date_line")
old_date=$(date -d "$old_date_string" +"%s")

if [ $old_date -ge $new_date ];
then
    ynh_print_info "No new version available. Skipping download."
    ynh_safe_rm "$install_dir/hashes_new.txt"
    exit 0
fi

find "$install_dir" -type f -maxdepth 1 -execdir rm -f {} \;

download_and_extract_monero

### $install_dir will automatically be initialized with some decent
### permissions by default... however, you may need to recursively reapply
### ownership to all files such as after the ynh_setup_source step
chown -R "$app:www-data" "$install_dir"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
# just restore everything from the backups; the tor & i2p hidden service directories should be there
# so those addresses should be the same so we shouldn't need to modify anything
bash restore

chown "$app:$app" "$install_dir/monerod.conf"

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

### This should be a literal copypaste of what happened in the install's "System configuration" section

ynh_config_add_systemd

ynh_config_add_logrotate "$data_dir/monero.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
